CREATE TABLE IF NOT EXISTS feeds (
	id INTEGER PRIMARY KEY,
	feed_url TEXT NOT NULL UNIQUE,
	site_url TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL DEFAULT '',
	etag TEXT NOT NULL DEFAULT '',
	last_modified TEXT NOT NULL DEFAULT '',
	last_fetched_at DATETIME,
	last_error TEXT,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS articles (
	id INTEGER PRIMARY KEY,
	feed_id INTEGER NOT NULL REFERENCES feeds(id) ON DELETE CASCADE,
	guid TEXT NOT NULL,
	url TEXT NOT NULL,
	title TEXT NOT NULL,
	content TEXT NOT NULL DEFAULT '',
	published_at DATETIME,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(feed_id, guid)

);

CREATE INDEX IF NOT EXISTS idx_articles_feed_id on articles(feed_id);
CREATE INDEX IF NOT EXISTS idx_articles_published_at on articles(published_at DESC);
